import { Language } from '../component/language/Language'
import User from '../view/user/User'
import Admin from '../view/admin/Admin'
import ProfilePage from '../view/profilePage/ProfilePage'
import CAtegory from '../view/category/Category'
import Restaurant from '../view/restaurantList/Restaurant'
import UserList from '../view/userList/UserList'
import Product from '../view/product/Product'
import FoodCategory from '../view/category/foodCategory/FoodCategory'
import Company from '../view/company/Company'
import Food from '../view/food/Food'
import Contract from '../view/contract/Contract'
import {
    FormOutlined,
    InboxOutlined,
    SettingOutlined,
    UsergroupAddOutlined,
    AppstoreOutlined,
    PieChartOutlined,
    LayoutOutlined,
    CoffeeOutlined,
    FileDoneOutlined,
} from '@ant-design/icons'

const {
    restaurantList,
    updateProfile,
    Category,
    userList,
    Products,
    Foods,
    Firms,
    FoodCategories,
    contract,
} = Language

export const _route = [
    {
        key: '1',
        to: '/',
        path: '/',
        component: Restaurant,
        name: restaurantList,
        roleSupperAdmin: true,
        roleAdmin: false,
        roleUser: false,
        icon: <FormOutlined />,
        type: true,
        b: true,
    },
    {
        key: '2',
        to: '/admin',
        path: '/admin',
        component: Admin,
        name: restaurantList,
        roleSupperAdmin: false,
        roleAdmin: true,
        roleUser: false,
        icon: 'Icon',
        type: true,
    },
    {
        key: '3',
        to: '/profile-page',
        path: '/profile-page',
        component: ProfilePage,
        name: updateProfile,
        role: true,
        icon: <SettingOutlined />,
        type: true,
        b: true,
    },
    {
        key: '4',
        to: 'category',
        path: '/:id/category',
        component: CAtegory,
        name: Category,
        roleSupperAdmin: true,
        roleAdmin: true,
        roleUser: false,
        icon: <AppstoreOutlined />,
        type: true,
        a: true,
    },
    {
        key: '5',
        to: '/user',
        path: '/user',
        component: User,
        name: restaurantList,
        roleSupperAdmin: false,
        roleAdmin: false,
        roleUser: true,
        icon: 'Icon',
        type: false,
    },
    {
        key: '6',
        to: '/user-list',
        path: '/user-list',
        component: UserList,
        name: userList,
        roleSupperAdmin: true,
        roleAdmin: false,
        roleUser: false,
        icon: <UsergroupAddOutlined />,
        type: true,
    },
    {
        key: '7',
        to: 'product',
        path: '/:id/product',
        component: Product,
        name: Products,
        roleSupperAdmin: true,
        roleAdmin: true,
        roleUser: false,
        icon: <InboxOutlined />,
        type: true,
        a: true,
    },
    {
        key: '8',
        to: 'foodCategory',
        path: '/:id/foodCategory',
        component: FoodCategory,
        name: FoodCategories,
        roleSupperAdmin: true,
        roleAdmin: true,
        roleUser: false,
        icon: <PieChartOutlined />,
        type: true,
        a: true,
    },
    {
        key: '9',
        to: 'company',
        path: '/:id/company',
        component: Company,
        name: Firms,
        roleSupperAdmin: true,
        roleAdmin: true,
        roleUser: false,
        icon: <LayoutOutlined />,
        type: true,
        a: true,
    },
    {
        key: '10',
        to: 'food',
        path: '/:id/food',
        component: Food,
        name: Foods,
        roleSupperAdmin: true,
        roleAdmin: true,
        roleUser: false,
        icon: <CoffeeOutlined />,
        type: true,
        a: true,
    },
    {
        key: '11',
        to: 'contract',
        path: '/:id/contract',
        component: Contract,
        name: contract,
        roleSupperAdmin: true,
        roleAdmin: true,
        roleUser: false,
        icon: <FileDoneOutlined />,
        type: true,
        a: true, // nimaga kere buu?
    },
]
